### ISSUE TITLE
add rdfs:isDefinedBy (instead of cims:belongsToCategory)

### ISSUE THREAD

**Issue by VladimirAlexiev** [Sveino/CIM4Diagram#17]
As per https://github.com/Sveino/Inst4CIM-KG/issues/103:
now that you have ontology modules, each term should have  rdfs:isDefinedBy (and not cims:belongsToCategory), eg:
```ttl
cim:IdentifiedObject a owl:Class ;
    rdfs:isDefinedBy <https://cim.ucaiug.io/ns/core> ;

cim:IdentifiedObject.name a owl:DatatypeProperty, owl:FunctionalProperty ;
    rdfs:isDefinedBy <https://cim.ucaiug.io/ns/core> ;
```

**Comment by Sveino** [comment]
Yes. We should use rdfs:isDefinedBy.

**Comment by bartkl** [comment]
For LinkML, I see these options:

### 1. Use `owned_by`

```yaml
classes:
  IdentifiedObject:
    owned_by: https://cim.ucaiug.io/ns/core
```

* Uses actual metaslot [`owned_by`](https://linkml.io/linkml-model/latest/docs/owned_by/) rather than our own extension with no formal semantics
* In the metamodel this metaslot is related to `rdfs:isDefinedBy` through a `skos:closeMatch`

### 2. Use annotation

If we think `owned_by` is not exact enough, we can use an annotation to create an informal language extension:

```yaml
classes:
  IdentifiedObject:
    annotations:
      is_defined_by: https://cim.ucaiug.io/ns/core
```

* More precise meaning and name
* Note the name follows the LinkML snake case convention, but it's not clear this corresponds to `rdfs:isDefinedBy`

### 3. Use annotation with RDFS term

```yaml
classes:
  IdentifiedObject:
    annotations:
      rdfs:isDefinedBy: https://cim.ucaiug.io/ns/core
```

* Again: precise meaning and name
* Reversed: the LinkML snake case convention is not followed, but it's explicitly clear we mean `rdfs:isDefinedBy`

## Discussion

I think `used_by` being close is close enough for me 😉 . Our parser could be the single source of truth of how to interpret this, and have it map to `rdfs:isDefinedBy`. Explicit in the model would be better, but  I like relying on the LinkML metamodel, because that way we keep responsibility on their end. I am not so sure.

What do you think? @Sveino @VladimirAlexiev
