### ISSUE TITLE
Use of cims

### ISSUE THREAD

**Issue by Sveino** [Sveino/CIM4Diagram#6]
Currently we use:

```Turtle
@prefix cims: <http://iec.ch/TC57/1999/rdf-schema-extensions-19990926#> .
@prefix uml: <http://iec.ch/TC57/NonStandard/UML#> 

  cims:multiplicity cims:M:1..1 ;
  cims:stereotype uml:attribute ;
```

I like this for backwards combability and increased clarity. Would like to add 

`    cims:stereotype uml:abstract . `

**Comment by bartkl** [comment]
The way I would probably represent this in LinkML is as follows:

```yaml
Person:
    attributes:
      name:
        required: true
        multivalued: true
      annotations:
        cims:stereotype: uml:attribute
```

And then have the RDFS generator understand that:

* `required: true` and `multivalued: true` maps to `<Person.name> cims:multiplicity cims:M:1..1`
* annotations that have the shape of a URI (with prefix defined) could be assumed to be extra annotating assertions, yielding `<Person.name> cims:stereotype uml:attribute`
