### ISSUE TITLE
skos:defintion vs rdfs:comment

### ISSUE THREAD

**Issue by Sveino** [Sveino/CIM4Diagram#7]
Should we use:

```Turtle
cim:IdentifiedObject a owl:Class ;
    rdfs:label "IdentifiedObject"@en ;
    skos:definition "This is a root class to provide common identification for all classes needing identification and naming attributes."@en .
```

or

```Turtle
cim:IdentifiedObject a owl:Class ;
    rdfs:label "IdentifiedObject"@en ;
    rdfs:comment "This is a root class to provide common identification for all classes needing identification and naming attributes."@en .
```

I prefer skos:definition, this is used in [DX PROF](https://www.w3.org/TR/dx-prof/rdf/prof.ttl) and [DCAT-3](https://www.w3.org/ns/dcat3.ttl). But not used in IDO...

**Comment by bartkl** [comment]
Given that the CIM does not define a taxonomy/controlled vocabulary, I think it makes sense to opt for the more specific meaning of `skos:definition` rather than the more generic `rdfs:comment`, to convey that you are actually providing a natural language definition for humans, as opposed to just comment (for humans also, of course).

But I would definitely like to hear what more experienced ontologists would have to say about this.

**Comment by VladimirAlexiev** [comment]
- `rdfs:comment` is traditionally used in ontologies.
- IDO just follows that tradition (@johanwk)
- DCAT goes to the extra length of using both, and having redundant text: `comment=definition+scopeNote`:
```
 rdfs:comment "A curated collection of metadata about resources (e.g., datasets and data services in the context of a data catalog)."@en ;
  skos:definition "A curated collection of metadata about resources."@en ;
  skos:editorialNote "Multilingual text not completelly updated. Translations for skos:scopeNote and definitions to doublecheck."@en ;
  skos:scopeNote "A web-based data catalog is typically represented as a single instance of this class."@en ;
  skos:scopeNote "Datasets and data services are examples of resources in the context of a data catalog."@en ;
```

This is a good approach, but splitting CIM comments into `definition` vs `scopeNote` is a lot of work.

**Comment by johanwk** [comment]
Our good friends at the Industrial Ontology Foundry have produced a great set of annotation properties. I think this is the stuff: https://spec.industrialontologies.org/iof/ontology/core/meta/AnnotationVocabulary/

rdfs:comment should still be provided (against the explicit advice of the IOF-av rules), simply to conform to expectations.

**Comment by Sveino** [comment]
I have added the relevant Annotation from : https://spec.industrialontologies.org/iof/ontology/core/meta/AnnotationVocabulary/

@VladimirAlexiev Agree with your comments. The default use shall be `rdfs:comment` this will include the same information that `skos:definition` plus `skos:scopeNote`. We can slowly move in the direction to clearly make a definition. It could be that we first tag that is noe a definition or the other way.

**Comment by bartkl** [comment]
In LinkML, I would look for these two options:

### 1. Use `description`

```yaml
classes:
  IdentifiedObject:
    description: This is a root class to provide common identification for all classes needing identification and naming attributes.
```

The metamodel defines this metaslot as follows:

```yaml
  description:
    rank: 5
    aliases:
      - definition
    domain: element
    description: >-
      a textual description of the element's purpose and use
    slot_uri: skos:definition
    exact_mappings:
      - dcterms:description
      - schema:description
    recommended: true
    in_subset:
      - BasicSubset
```

* It is one of the most common fields to use, recognized by most people and software, and is honestly pretty much expected to be present (note the `recommended: true` also)
* However, it is a `skos:definition` fomally, which in the RDFS we decided against (for now)

### 2. Use `comments`

```yaml
classes:
  IdentifiedObject:
    comments:
      - This is a root class to provide common identification for all classes needing identification and naming attributes.
```

The metamodel defines this metaslot as follows:

```yaml
  comments:
    domain: element
    multivalued: true
    description: notes and comments about an element intended primarily for external consumption
    slot_uri: skos:note
    exact_mappings:
      - rdfs:comment
    in_subset:
      - BasicSubset
```

* Not as common as `description`
* Multivalued, which gives us options but is cumbersome for the main description (in CIM we always have one also?)
* It does match up semantically with the route we took with RDFS, namely `rdfs:comment`.

## Discussion

I find it difficult to argue against `description` here, it's just one of the most natural and commonplace fields for any element. I don't think we need to align the RDFS and LinkML choices 100%, but I need your input for that. So what do you think @VladimirAlexiev @Sveino
